import os
from snakemake.utils import min_version
min_version("9.3.3")

configfile: "config.yaml"

include: "rules/common.smk"
include: "rules/qc_fastp.smk"
include: "rules/align_star.smk"
include: "rules/cage_ctss.smk"

MULTIQC_TARGET = (
    f"{OUTDIR}/qc/multiqc/multiqc_report.html"
    if config.get("generate_multiqc", True)
    else None
)

PRIMARY_TARGETS = []
PRIMARY_TARGETS += expand(f"{OUTDIR}/qc/fastp/{{sample}}/merged_fastp_final.html", sample=SAMPLES)
PRIMARY_TARGETS += expand(f"{OUTDIR}/qc/fastp/{{sample}}/merged_fastp_final.json", sample=SAMPLES)
if MULTIQC_TARGET:
    PRIMARY_TARGETS.append(MULTIQC_TARGET)
if KEEP_BAM:
    PRIMARY_TARGETS += [final_bam_path(sample) for sample in SAMPLES]
    PRIMARY_TARGETS += [final_bai_path(sample) for sample in SAMPLES]
PRIMARY_TARGETS += expand(f"{OUTDIR}/ctss/{{sample}}/{{sample}}.ctss.tsv", sample=SAMPLES)
PRIMARY_TARGETS += expand(f"{OUTDIR}/bigwig/{{sample}}/{{sample}}.5prime.raw.bw", sample=SAMPLES)
PRIMARY_TARGETS += expand(f"{OUTDIR}/bigwig/{{sample}}/{{sample}}.5prime.cpm.bw", sample=SAMPLES)
PRIMARY_TARGETS += expand(f"{OUTDIR}/cager/{{sample}}/{{sample}}_tagClusters.bed", sample=SAMPLES)
rule all:
    input:
        PRIMARY_TARGETS
